---
- hosts: localhost
  become: True
  become_user: root

  vars:
    local_user: "{{ lookup('env','USER') }}"
    local_user_home: "{{ lookup('env','HOME') }}"
    docker_compose_release: "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64"

  pre_tasks:
    - name: Update repository
      apt: 
        update_cache: yes
        cache_valid_time: 3600

    - name: autoclean
      apt:
        autoclean: yes

  roles:
    - base
    - docker
    #- utils